import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { AppShell } from "../components/AppShell.jsx";
import { LoadingPage } from "../components/Spinner.jsx";
import { EmptyState, ErrorState, ProgressBar } from "../components/States.jsx";
export default function DashboardPage() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const fetchData = () => { setLoading(true); setError(false); fetch("/api/dashboard").then((r)=>r.json()).then((d)=>{if(d.error)throw new Error();setData(d);}).catch(()=>setError(true)).finally(()=>setLoading(false)); };
  useEffect(() => { fetchData(); }, []);
  if (loading) return <AppShell><LoadingPage /></AppShell>;
  if (error || !data) return <AppShell><ErrorState onRetry={fetchData} /></AppShell>;
  const { stats, subjectProgress, recentNotes, recentQuizzes } = data;
  const hasData = stats.totalSubjects > 0;
  return (<AppShell><div className="space-y-6">
    <div><h1 className="text-2xl font-bold text-gray-900">Dashboard</h1><p className="text-sm text-gray-500 mt-1">Your study progress at a glance</p></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[{label:"Subjects",value:stats.totalSubjects,icon:"📚",color:"bg-blue-50 text-blue-600"},{label:"Topics Completed",value:`${stats.completedTopics}/${stats.totalTopics}`,icon:"✅",color:"bg-green-50 text-green-600"},{label:"Notes",value:stats.totalNotes,icon:"📝",color:"bg-amber-50 text-amber-600"},{label:"Avg Quiz Score",value:`${stats.avgScore}%`,icon:"🎯",color:"bg-purple-50 text-purple-600"}].map((s)=>(<div key={s.label} className="bg-white rounded-xl shadow-sm border border-gray-100 p-5"><div className="flex items-center gap-3"><div className={`w-10 h-10 rounded-lg flex items-center justify-center text-lg ${s.color}`}>{s.icon}</div><div><p className="text-2xl font-bold text-gray-900">{s.value}</p><p className="text-xs text-gray-500">{s.label}</p></div></div></div>))}</div>
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5"><div className="flex items-center justify-between mb-4"><h2 className="font-semibold text-gray-900">Subject Progress</h2><Link to="/subjects" className="text-sm text-indigo-600 hover:underline">View all →</Link></div>{subjectProgress.length===0 ? <EmptyState icon="📚" title="No subjects yet" description="Create your first subject to start tracking progress" action={<Link to="/subjects" className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 text-sm">Create Subject</Link>} /> : <div className="space-y-3">{subjectProgress.map((s)=>(<Link key={s.id} to={`/subjects/${s.id}`} className="block p-3 rounded-lg hover:bg-gray-50"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2"><div className="w-3 h-3 rounded-full" style={{background:s.color}} /><span className="font-medium text-gray-800">{s.name}</span></div><span className="text-sm text-gray-500">{s.completedTopics}/{s.totalTopics} topics · {s.noteCount} notes</span></div><ProgressBar value={s.progress} /></Link>))}</div>}</div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5"><div className="flex items-center justify-between mb-3"><h2 className="font-semibold text-gray-900">Recent Notes</h2><Link to="/notes" className="text-sm text-indigo-600 hover:underline">View all →</Link></div>{recentNotes.length===0 ? <p className="text-sm text-gray-400 py-4 text-center">No notes yet</p> : <div className="space-y-2">{recentNotes.map((n)=>(<Link key={n.id} to={`/notes/${n.id}`} className="block p-2 rounded-lg hover:bg-gray-50"><p className="text-sm font-medium text-gray-800 truncate">{n.title}</p><p className="text-xs text-gray-400">{new Date(n.updatedAt).toLocaleDateString("en-IN")}</p></Link>))}</div>}</div><div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5"><div className="flex items-center justify-between mb-3"><h2 className="font-semibold text-gray-900">Recent Quizzes</h2><Link to="/quizzes" className="text-sm text-indigo-600 hover:underline">View all →</Link></div>{recentQuizzes.length===0 ? <p className="text-sm text-gray-400 py-4 text-center">No quizzes yet</p> : <div className="space-y-2">{recentQuizzes.map((q)=>(<Link key={q.id} to={`/quizzes/${q.id}`} className="block p-2 rounded-lg hover:bg-gray-50"><div className="flex items-center justify-between"><p className="text-sm font-medium text-gray-800 truncate">{q.title}</p>{q.score!==null && <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-50 text-green-600 ml-2">{q.score}%</span>}</div></Link>))}</div>}</div></div>
    {!hasData && <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 text-center py-12"><div className="text-5xl mb-3">🚀</div><h2 className="text-lg font-semibold text-gray-800 mb-2">Get Started</h2><p className="text-sm text-gray-500 mb-4">Create a subject, add topics, write notes, and let AI help you study smarter.</p><Link to="/subjects" className="inline-block px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700">Create Your First Subject</Link></div>}
  </div></AppShell>);
}
