import React, { useEffect, useState } from "react";
import { useSearchParams, Link } from "react-router-dom";
import { AppShell } from "../components/AppShell.jsx";
import { LoadingPage } from "../components/Spinner.jsx";
import { EmptyState, ErrorState } from "../components/States.jsx";
import { useToast } from "../components/Toaster.jsx";
export default function NotesPage() {
  const [searchParams] = useSearchParams(); const { showToast } = useToast();
  const [notes, setNotes] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const [search, setSearch] = useState(""); const [showForm, setShowForm] = useState(!!searchParams.get("topicId")); const [creating, setCreating] = useState(false);
  const [topics, setTopics] = useState([]); const [form, setForm] = useState({ title:"", content:"", topicId: searchParams.get("topicId")||"" });
  const topicIdFilter = searchParams.get("topicId");
  const fetchNotes = () => { setLoading(true); setError(false); const p = new URLSearchParams(); if(search)p.set("search",search); if(topicIdFilter)p.set("topicId",topicIdFilter); fetch(`/api/notes?${p}`).then((r)=>r.json()).then((d)=>{if(d.error)throw new Error();setNotes(d.notes||[]);}).catch(()=>setError(true)).finally(()=>setLoading(false)); };
  useEffect(() => { fetch("/api/topics").then((r)=>r.json()).then((d)=>{if(d.topics)setTopics(d.topics.map(t=>({id:t.id,name:t.name,subjectName:t.subjectName})));}); }, []);
  useEffect(() => { fetchNotes(); }, [search, topicIdFilter]);
  const handleCreate = async (e) => { e.preventDefault(); if(!form.title.trim()||!form.content.trim()) return; setCreating(true); try { const res = await fetch("/api/notes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const data=await res.json(); if(!res.ok){showToast(data.error||"Failed","error");return;} showToast("Note created!","success"); window.location.href=`/notes/${data.note.id}`; } catch { showToast("Network error","error"); } finally { setCreating(false); } };
  if (loading&&notes.length===0) return <AppShell><LoadingPage /></AppShell>;
  if (error) return <AppShell><ErrorState onRetry={fetchNotes} /></AppShell>;
  return (<AppShell><div className="space-y-6">
    <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-gray-900">Notes</h1><p className="text-sm text-gray-500 mt-1">{topicIdFilter?"Filtered by topic":"All your study notes"}</p></div><button onClick={()=>setShowForm(!showForm)} className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 text-sm">{showForm?"Cancel":"+ New Note"}</button></div>
    {showForm && <form onSubmit={handleCreate} className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 space-y-3 animate-slide-up"><div><label className="block text-sm font-medium text-gray-700 mb-1">Title</label><input type="text" className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" placeholder="Note title" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} disabled={creating} /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Content</label><textarea className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" placeholder="Write your notes here..." value={form.content} onChange={(e)=>setForm({...form,content:e.target.value})} rows={5} disabled={creating} /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Topic (optional)</label><select className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" value={form.topicId} onChange={(e)=>setForm({...form,topicId:e.target.value})} disabled={creating}><option value="">No topic</option>{topics.map((t)=>(<option key={t.id} value={t.id}>{t.name} ({t.subjectName})</option>))}</select></div><button type="submit" className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50" disabled={creating||!form.title.trim()||!form.content.trim()}>{creating?"Creating...":"Create Note"}</button></form>}
    <div className="relative"><input type="text" className="w-full px-3 py-2 pl-10 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" placeholder="Search notes..." value={search} onChange={(e)=>setSearch(e.target.value)} /><span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">🔍</span></div>
    {notes.length===0 ? <EmptyState icon="📝" title={search?"No matching notes":"No notes yet"} description={search?"Try a different search term":"Create your first note"} action={!showForm&&!search?<button onClick={()=>setShowForm(true)} className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 text-sm">+ New Note</button>:undefined} /> : <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{notes.map((n)=>(<Link key={n.id} to={`/notes/${n.id}`} className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 hover:shadow-md transition-shadow"><h3 className="font-semibold text-gray-900 truncate mb-1">{n.title}</h3><p className="text-sm text-gray-500 line-clamp-3 mb-3">{n.content}</p><div className="flex items-center justify-between text-xs text-gray-400"><span>{new Date(n.updatedAt).toLocaleDateString("en-IN")}</span>{n.subjectName&&<span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full" style={{background:n.subjectColor||"#6366f1"}} />{n.subjectName}</span>}</div></Link>))}</div>}
  </div></AppShell>);
}
