import React, { useEffect, useState } from "react";
import { useSearchParams, Link } from "react-router-dom";
import { AppShell } from "../components/AppShell.jsx";
import { LoadingPage } from "../components/Spinner.jsx";
import { EmptyState, ErrorState } from "../components/States.jsx";
import { useToast } from "../components/Toaster.jsx";
import { Spinner } from "../components/Spinner.jsx";
export default function QuizzesPage() {
  const [searchParams] = useSearchParams(); const { showToast } = useToast();
  const [quizzes, setQuizzes] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const [topics, setTopics] = useState([]); const [generating, setGenerating] = useState(false);
  const [showGenerator, setShowGenerator] = useState(!!searchParams.get("generate"));
  const [genTopicId, setGenTopicId] = useState(searchParams.get("topicId")||""); const [genNum, setGenNum] = useState(5);
  const fetchQuizzes = () => { setLoading(true); setError(false); fetch("/api/quiz").then((r)=>r.json()).then((d)=>{if(d.error)throw new Error();setQuizzes(d.quizzes||[]);}).catch(()=>setError(true)).finally(()=>setLoading(false)); };
  useEffect(() => { fetchQuizzes(); fetch("/api/topics").then((r)=>r.json()).then((d)=>{if(d.topics)setTopics(d.topics.map(t=>({id:t.id,name:t.name,subjectName:t.subjectName})));}); }, []);
  const handleGenerate = async (e) => { e.preventDefault(); if(!genTopicId){showToast("Select a topic","error");return;} setGenerating(true); try { const res=await fetch("/api/quiz/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topicId:genTopicId,numQuestions:genNum})}); const data=await res.json(); if(!res.ok){showToast(data.error||"Failed","error");return;} const topic=topics.find(t=>t.id===genTopicId); const saveRes=await fetch("/api/quiz",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:`Quiz: ${data.topicName||topic?.name||"Topic"}`,topicId:genTopicId,questions:data.questions,score:null})}); const saveData=await saveRes.json(); if(saveRes.ok&&saveData.quiz){showToast("Quiz generated!","success");window.location.href=`/quizzes/${saveData.quiz.id}`;}else showToast("Failed to save","error"); } catch { showToast("Network error","error"); } finally { setGenerating(false); } };
  const handleDelete = async (qid) => { if(!confirm("Delete this quiz?")) return; const res=await fetch(`/api/quiz/${qid}`,{method:"DELETE"}); if(res.ok){showToast("Quiz deleted","success");fetchQuizzes();} };
  if (loading) return <AppShell><LoadingPage /></AppShell>;
  if (error) return <AppShell><ErrorState onRetry={fetchQuizzes} /></AppShell>;
  return (<AppShell><div className="space-y-6">
    <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-gray-900">Quizzes</h1><p className="text-sm text-gray-500 mt-1">AI-generated quizzes from your topics</p></div><button onClick={()=>setShowGenerator(!showGenerator)} className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 text-sm">{showGenerator?"Cancel":"✨ Generate Quiz"}</button></div>
    {showGenerator && <form onSubmit={handleGenerate} className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 space-y-4 animate-slide-up"><div><label className="block text-sm font-medium text-gray-700 mb-1">Select Topic</label><select className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" value={genTopicId} onChange={(e)=>setGenTopicId(e.target.value)} disabled={generating}><option value="">Choose a topic...</option>{topics.map((t)=>(<option key={t.id} value={t.id}>{t.name} ({t.subjectName})</option>))}</select>{topics.length===0&&<p className="text-xs text-gray-400 mt-1">No topics available. Create subjects and topics first.</p>}</div><div><label className="block text-sm font-medium text-gray-700 mb-1">Questions: {genNum}</label><input type="range" min="1" max="10" value={genNum} onChange={(e)=>setGenNum(Number(e.target.value))} disabled={generating} className="w-full" /></div><button type="submit" className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50" disabled={generating||!genTopicId}>{generating?<span className="flex items-center gap-2"><Spinner size="sm"/> Generating...</span>:"Generate Quiz"}</button></form>}
    {quizzes.length===0 ? <EmptyState icon="✅" title="No quizzes yet" description="Generate AI-powered quizzes from your topics" action={!showGenerator?<button onClick={()=>setShowGenerator(true)} className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 text-sm">✨ Generate Quiz</button>:undefined} /> : <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{quizzes.map((q)=>(<div key={q.id} className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 group"><Link to={`/quizzes/${q.id}`} className="block"><h3 className="font-semibold text-gray-900 truncate mb-2">{q.title}</h3><div className="flex items-center gap-2 text-sm">{q.subjectName&&<span className="flex items-center gap-1 text-gray-500"><span className="w-2 h-2 rounded-full" style={{background:q.subjectColor||"#6366f1"}} />{q.subjectName}</span>}{q.topicName&&<span className="text-gray-400">→ {q.topicName}</span>}</div>{q.score!==null&&<div className="mt-2"><span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${q.score>=70?"bg-green-50 text-green-600":"bg-amber-50 text-amber-600"}`}>Score: {q.score}%</span></div>}</Link><button onClick={()=>handleDelete(q.id)} className="text-xs text-red-400 hover:text-red-600 mt-3 opacity-0 group-hover:opacity-100 transition-opacity">Delete</button></div>))}</div>}
  </div></AppShell>);
}
