import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { AppShell } from "../components/AppShell.jsx";
import { LoadingPage } from "../components/Spinner.jsx";
import { EmptyState, ErrorState } from "../components/States.jsx";
import { useToast } from "../components/Toaster.jsx";
import { Spinner } from "../components/Spinner.jsx";
const COLORS = ["#6366f1","#ef4444","#f59e0b","#10b981","#3b82f6","#8b5cf6","#ec4899","#14b8a6"];
export default function SubjectsPage() {
  const { showToast } = useToast();
  const [subjects, setSubjects] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const [showForm, setShowForm] = useState(false); const [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ name: "", description: "", color: COLORS[0] });
  const fetchSubjects = () => { setLoading(true); setError(false); fetch("/api/subjects").then((r)=>r.json()).then((d)=>{if(d.error)throw new Error();setSubjects(d.subjects||[]);}).catch(()=>setError(true)).finally(()=>setLoading(false)); };
  useEffect(() => { fetchSubjects(); }, []);
  const handleCreate = async (e) => { e.preventDefault(); if (!form.name.trim()) return; setCreating(true); try { const res = await fetch("/api/subjects", { method: "POST", headers: {"Content-Type":"application/json"}, body: JSON.stringify(form) }); const data = await res.json(); if (!res.ok) { showToast(data.error||"Failed","error"); return; } showToast("Subject created!","success"); setForm({name:"",description:"",color:COLORS[0]}); setShowForm(false); fetchSubjects(); } catch { showToast("Network error","error"); } finally { setCreating(false); } };
  const handleDelete = async (id) => { if (!confirm("Delete this subject and all its topics and notes?")) return; const res = await fetch(`/api/subjects/${id}`,{method:"DELETE"}); if (res.ok) { showToast("Subject deleted","success"); fetchSubjects(); } else showToast("Failed","error"); };
  if (loading) return <AppShell><LoadingPage /></AppShell>;
  if (error) return <AppShell><ErrorState onRetry={fetchSubjects} /></AppShell>;
  return (<AppShell><div className="space-y-6">
    <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-gray-900">Subjects</h1><p className="text-sm text-gray-500 mt-1">Organize your studies by subject</p></div><button onClick={()=>setShowForm(!showForm)} className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 text-sm">{showForm?"Cancel":"+ New Subject"}</button></div>
    {showForm && <form onSubmit={handleCreate} className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 space-y-4 animate-slide-up"><div><label className="block text-sm font-medium text-gray-700 mb-1">Subject Name</label><input type="text" className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" placeholder="e.g., Mathematics" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} disabled={creating} /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Description (optional)</label><textarea className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" placeholder="Brief description..." value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} rows={2} disabled={creating} /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Color</label><div className="flex gap-2 flex-wrap">{COLORS.map((c)=>(<button key={c} type="button" onClick={()=>setForm({...form,color:c})} className={`w-8 h-8 rounded-full ${form.color===c?"ring-2 ring-offset-2 ring-gray-400":""}`} style={{background:c}} />))}</div></div><button type="submit" className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50" disabled={creating||!form.name.trim()}>{creating?<Spinner size="sm"/>:"Create Subject"}</button></form>}
    {subjects.length===0 ? <EmptyState icon="📚" title="No subjects yet" description="Create your first subject to start organizing your studies" action={!showForm?<button onClick={()=>setShowForm(true)} className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 text-sm">+ New Subject</button>:undefined} /> : <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{subjects.map((s)=>(<div key={s.id} className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 hover:shadow-md transition-shadow group"><Link to={`/subjects/${s.id}`} className="block"><div className="flex items-start gap-3 mb-3"><div className="w-1 h-12 rounded-full" style={{background:s.color}} /><div className="flex-1 min-w-0"><h3 className="font-semibold text-gray-900 truncate">{s.name}</h3>{s.description&&<p className="text-sm text-gray-500 line-clamp-2">{s.description}</p>}</div></div><div className="flex gap-3 text-xs text-gray-500"><span>{s.topicCount} topics</span><span>{s.noteCount} notes</span></div></Link><button onClick={()=>handleDelete(s.id)} className="text-xs text-red-400 hover:text-red-600 mt-3 opacity-0 group-hover:opacity-100 transition-opacity">Delete</button></div>))}</div>}
  </div></AppShell>);
}
