import React, { useEffect, useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { AppShell } from "../components/AppShell.jsx";
import { LoadingPage } from "../components/Spinner.jsx";
import { EmptyState, ErrorState, ProgressBar } from "../components/States.jsx";
import { useToast } from "../components/Toaster.jsx";
export default function SubjectDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { showToast } = useToast();
  const [subject, setSubject] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const [showForm, setShowForm] = useState(false); const [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ name: "", description: "" });
  const fetchSubject = () => { setLoading(true); setError(false); fetch(`/api/subjects/${id}`).then((r)=>r.json()).then((d)=>{if(d.error)throw new Error();setSubject(d.subject);}).catch(()=>setError(true)).finally(()=>setLoading(false)); };
  useEffect(() => { fetchSubject(); }, [id]);
  const handleAddTopic = async (e) => { e.preventDefault(); if (!form.name.trim()) return; setCreating(true); try { const res = await fetch("/api/topics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,subjectId:id})}); const data=await res.json(); if(!res.ok){showToast(data.error||"Failed","error");return;} showToast("Topic added!","success"); setForm({name:"",description:""}); setShowForm(false); fetchSubject(); } catch { showToast("Network error","error"); } finally { setCreating(false); } };
  const toggleTopic = async (tid, comp) => { const res = await fetch(`/api/topics/${tid}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({completed:!comp})}); if(res.ok) fetchSubject(); };
  const handleDeleteTopic = async (tid) => { if(!confirm("Delete this topic?")) return; const res = await fetch(`/api/topics/${tid}`,{method:"DELETE"}); if(res.ok){showToast("Topic deleted","success");fetchSubject();} };
  if (loading) return <AppShell><LoadingPage /></AppShell>;
  if (error||!subject) return <AppShell><ErrorState onRetry={fetchSubject} /></AppShell>;
  const cc = subject.topics.filter(t=>t.completed).length;
  const prog = subject.topics.length>0?Math.round((cc/subject.topics.length)*100):0;
  return (<AppShell><div className="space-y-6">
    <div><Link to="/subjects" className="text-sm text-gray-500 hover:underline">← Back to Subjects</Link><div className="flex items-center gap-3 mt-2"><div className="w-1 h-10 rounded-full" style={{background:subject.color}} /><div className="flex-1"><h1 className="text-2xl font-bold text-gray-900">{subject.name}</h1>{subject.description&&<p className="text-sm text-gray-500">{subject.description}</p>}</div></div><div className="mt-3 max-w-xs"><div className="flex justify-between text-xs text-gray-500 mb-1"><span>Progress</span><span>{cc}/{subject.topics.length} topics</span></div><ProgressBar value={prog} /></div></div>
    <div className="flex items-center justify-between"><h2 className="font-semibold text-gray-900">Topics</h2><button onClick={()=>setShowForm(!showForm)} className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 text-sm">{showForm?"Cancel":"+ Add Topic"}</button></div>
    {showForm && <form onSubmit={handleAddTopic} className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 space-y-3 animate-slide-up"><div><label className="block text-sm font-medium text-gray-700 mb-1">Topic Name</label><input type="text" className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" placeholder="e.g., Algebra" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} disabled={creating} /></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Description (optional)</label><input type="text" className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500" placeholder="Brief..." value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} disabled={creating} /></div><button type="submit" className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50" disabled={creating||!form.name.trim()}>{creating?"Adding...":"Add Topic"}</button></form>}
    {subject.topics.length===0 ? <EmptyState icon="📖" title="No topics yet" description="Add topics to organize your study material" action={!showForm?<button onClick={()=>setShowForm(true)} className="px-4 py-2 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 text-sm">+ Add Topic</button>:undefined} /> : <div className="space-y-2">{subject.topics.map((t)=>(<div key={t.id} className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 group"><div className="flex items-center gap-3"><button onClick={()=>toggleTopic(t.id,!!t.completed)} className={`w-5 h-5 rounded border-2 flex items-center justify-center flex-shrink-0 ${t.completed?"bg-green-500 border-green-500 text-white":"border-gray-300 hover:border-gray-400"}`}>{t.completed&&"✓"}</button><div className="flex-1 min-w-0"><h3 className={`font-medium ${t.completed?"text-gray-400 line-through":"text-gray-900"}`}>{t.name}</h3>{t.description&&<p className="text-sm text-gray-500 truncate">{t.description}</p>}</div><div className="text-xs text-gray-400">{t.noteCount||0} notes</div><div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity"><Link to={`/notes?topicId=${t.id}`} className="text-xs px-2 py-1 rounded bg-gray-100 hover:bg-gray-200 text-gray-600">Notes</Link><button onClick={()=>navigate(`/quizzes?generate=1&topicId=${t.id}`)} className="text-xs px-2 py-1 rounded bg-indigo-50 hover:bg-indigo-100 text-indigo-600">Quiz</button><button onClick={()=>handleDeleteTopic(t.id)} className="text-xs px-2 py-1 rounded bg-red-50 hover:bg-red-100 text-red-500">Delete</button></div></div></div>))}</div>}
  </div></AppShell>);
}
